# Generated by Django 6.1.1 on 2026-09-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_player_guild_alter_player_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255),
        ),
    ]
